name: Run OKX Alerts Script

on:
  schedule:
    - cron: '*/15 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install TA-Lib system library
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y wget
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.https://discord.com/api/webhooks/1377383087209451703/xnoJnt4PnHnZEiU2FLlYojnEdTnQqpZlK-F6oi7NiY1DAhGf8NGb21Ko_uBVqxOXbmN1 }}
        run: python okx_alerts/alerts.py
